version: '3.1'

services:
    app:
        image: node:latest
        restart: always
        privileged: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: production
            PORT: 5050
        ports:
            - "5050:5050"
        volumes:
            - '.:/home/app'
        network_mode: bridge
